spring:
  cloud:
    gateway:
      routes:
        - id: test_rout
          uri: https://www.baidu.com
          predicates:
              - Query=url, ba


        - id: qq_rout
          uri: https://www.qq.com
          predicates:
              - Query=url,qq